<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vnvpc130" name="RB_Release.Grid_DeleteRelease" tests="1" failures="1" timestamp="5 Jul 2012 14:26:59 GMT" time="159.357" errors="0">
  <testcase name="testGoogleSearch" time="159.357" classname="RB_Release.Grid_DeleteRelease">
    <failure type="com.thoughtworks.selenium.SeleniumException" message="ERROR: There was an unexpected Alert! [{&quot;error&quot;:{&quot;type&quot;:&quot;Web_Controller_Exception_InvalidInput&quot;,&quot;message&quot;:&quot;Invalid Input&quot;,&quot;code&quot;:500,&quot;file&quot;:&quot;\/var\/www\/html_beta\/vectorapi\/application\/services\/Releases.php&quot;,&quot;line&quot;:957,&quot;error_message_array&quot;:{&quot;error&quot;:&quot;NULL&quot;},&quot;remoteAddress&quot;:&quot;192.168.31.29&quot;,&quot;serverAddress&quot;:&quot;192.168.31.29&quot;,&quot;requestUrl&quot;:&quot;\/vectorapi\/release?data_format=json&amp;release_id=%5B254297%5D&amp;access_token=db157942a09f99c814cc4b95e377d282&amp;errorMode=1&quot;}}]">
      <![CDATA[com.thoughtworks.selenium.SeleniumException: ERROR: There was an unexpected Alert! [{"error":{"type":"Web_Controller_Exception_InvalidInput","message":"Invalid Input","code":500,"file":"\/var\/www\/html_beta\/vectorapi\/application\/services\/Releases.php","line":957,"error_message_array":{"error":"NULL"},"remoteAddress":"192.168.31.29","serverAddress":"192.168.31.29","requestUrl":"\/vectorapi\/release?data_format=json&release_id=%5B254297%5D&access_token=db157942a09f99c814cc4b95e377d282&errorMode=1"}}]
	at com.thoughtworks.selenium.HttpCommandProcessor.throwAssertionFailureExceptionOrError(HttpCommandProcessor.java:112)
	at com.thoughtworks.selenium.HttpCommandProcessor.doCommand(HttpCommandProcessor.java:106)
	at com.thoughtworks.selenium.DefaultSelenium.clickAt(DefaultSelenium.java:198)
	at RB_Release.Grid_DeleteRelease.testGoogleSearch(Grid_DeleteRelease.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:34)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:351)
	at org.testng.internal.thread.ThreadUtil$CountDownLatchedRunnable.run(ThreadUtil.java:147)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase>
</testsuite>
